# Generated by Django 3.2.8 on 2022-01-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica1', '0002_auto_20220127_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(max_length=2)),
                ('assenza', models.CharField(max_length=3)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materie', to='prova_pratica1.materia')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studente', to='prova_pratica1.studente')),
            ],
        ),
    ]
